import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { Locale, routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import { ThemeProvider } from '@/components/theme-provider';
import ReactQueryProvider from '@/lib/reactQueryProvider';
import { Toaster } from '@/components/ui/sonner';
import { ModeToggle } from '@/components/ModeToggle';
import LocaleSelector from '@/components/LocaleSelector';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import DynamicBreadcrumb from '@/components/DynamicBreadcrumb';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ReactQueryProvider>
						<NextIntlClientProvider>
							<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
								<SidebarProvider defaultOpen={true}>
									<AppSidebar />
									<SidebarInset>
										<div className="min-h-screen flex flex-col relative">
											<header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
												<div className="flex items-center gap-2 px-4">
													<SidebarTrigger className="-ml-1" />
													<Separator
													orientation="vertical"
													className="mr-2 data-[orientation=vertical]:h-4"
													/>
													<DynamicBreadcrumb />
												</div>
												<div className="z-90 absolute top-4 right-4 flex items-center gap-4">
													<LocaleSelector />
													<ModeToggle />
												</div>
											</header>
											<div className='h-full'>
												{children}
											</div>
											<Toaster />
										</div>
										<Footer />
									</SidebarInset>
								</SidebarProvider>
							</ThemeProvider>
						</NextIntlClientProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}

export async function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}
